---
galaxy_info:
  author: Andrew Rothstein
  description: terraform role
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 1.2
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Alpine
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - terraform
    - cloud
    - infrastructure

dependencies:
  - src: andrewrothstein.unarchive-deps
    version: v1.0.9
